title: Md. Arman Hossen
logo: /profile.jpg
description: >
  Postdoctoral Researcher in Astronomy and Astrophysics at Pennsylvania State University. 
  X-ray and gamma-ray detector development, Hybrid CMOS detectors, TES microcalorimeters, 
  and high-energy astrophysics instrumentation.

theme: jekyll-theme-minimal

show_downloads: false

github:
  is_project_page: false

plugins:
  - jekyll-seo-tag
